version: '3'

services:
  oracle-db:
    ports:
      - '1521:1521'
    container_name: oracle
    image: gvenzl/oracle-free
    environment:
      ORACLE_PASSWORD: SuperSecret0
    networks:
      - aplicaciones
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d



networks:
  aplicaciones:
    driver: bridge

